export const COUNTRY_NAMES = {
	US: { primary: "US", secondary: "United States" },
	AT: { primary: "AT", secondary: "Austria" },
	BE: { primary: "BE", secondary: "Belgium" },
	BG: { primary: "BG", secondary: "Bulgaria" },
	HR: { primary: "HR", secondary: "Croatia" },
	CY: { primary: "CY", secondary: "Cyprus" },
	CZ: { primary: "CZ", secondary: "Czech Republic" },
	DK: { primary: "DK", secondary: "Denmark" },
	EE: { primary: "EE", secondary: "Estonia" },
	FI: { primary: "FI", secondary: "Finland" },
	FR: { primary: "FR", secondary: "France" },
	DE: { primary: "DE", secondary: "Germany" },
	HU: { primary: "HU", secondary: "Hungary" },
	IE: { primary: "IE", secondary: "Republic of Ireland" },
	IT: { primary: "IT", secondary: "Italy" },
	LU: { primary: "LU", secondary: "Luxembourg" },
	MT: { primary: "MT", secondary: "Malta" },
	NL: { primary: "NL", secondary: "Netherlands" },
	NO: { primary: "NO", secondary: "Norway" },
	PL: { primary: "PL", secondary: "Poland" },
	PT: { primary: "PT", secondary: "Portugal" },
	RO: { primary: "RO", secondary: "Romania" },
	SK: { primary: "SK", secondary: "Slovak Republic" },
	SI: { primary: "SI", secondary: "Slovenia" },
	ES: { primary: "ES", secondary: "Spain" },
	SE: { primary: "SE", secondary: "Sweden" },
	AU: { primary: "AU", secondary: "Australia" },
	CA: { primary: "CA", secondary: "Canada" },
	NZ: { primary: "NZ", secondary: "New Zealand" },
	ZA: { primary: "ZA", secondary: "South Africa" },
	CH: { primary: "CH", secondary: "Switzerland" },
	GB: { primary: "GB", secondary: "United Kingdom" },
};

export const COUNTRY_VALUES = Object.keys(COUNTRY_NAMES);
