import { z } from 'zod';

export const SIGNUP_SCHEMA = z.object({
	firstName: z.string().nonempty("First name is required"),
	lastName: z.string().nonempty("Last name is required"),
	email: z.string().email("Invalid email format").nonempty("Email is required"),
	businessName: z.string().nonempty("Business name is required"),
	password: z.string().min(12, "Password must be at least 12 characters").nonempty("Password is required"),
});

export const COUNTRIES = [
	{ value: "US", label: "United States" },
	{ value: "AT", label: "Austria" },
	{ value: "BE", label: "Belgium" },
	{ value: "BG", label: "Bulgaria" },
	{ value: "HR", label: "Croatia" },
	{ value: "CY", label: "Cyprus" },
	{ value: "CZ", label: "Czech Republic" },
	{ value: "DK", label: "Denmark" },
	{ value: "EE", label: "Estonia" },
	{ value: "FI", label: "Finland" },
	{ value: "FR", label: "France" },
	{ value: "DE", label: "Germany" },
	{ value: "HU", label: "Hungary" },
	{ value: "IE", label: "Republic of Ireland" },
	{ value: "IT", label: "Italy" },
	{ value: "LU", label: "Luxembourg" },
	{ value: "MT", label: "Malta" },
	{ value: "NL", label: "Netherlands" },
	{ value: "NO", label: "Norway" },
	{ value: "PL", label: "Poland" },
	{ value: "PT", label: "Portugal" },
	{ value: "RO", label: "Romania" },
	{ value: "SK", label: "Slovak Republic" },
	{ value: "SI", label: "Slovenia" },
	{ value: "ES", label: "Spain" },
	{ value: "SE", label: "Sweden" },
	{ value: "AU", label: "Australia" },
	{ value: "CA", label: "Canada" },
	{ value: "NZ", label: "New Zealand" },
	{ value: "ZA", label: "South Africa" },
	{ value: "CH", label: "Switzerland" },
	{ value: "GB", label: "United Kingdom" },
];

export const COUNTRY_NAMES = {
	US: {primary: "US", secondary: "United States"},
	AT: {primary: "AT", secondary: "Austria"},
	BE: {primary: "BE", secondary: "Belgium"},
	BG: {primary: "BG", secondary: "Bulgaria"},
	HR: {primary: "HR", secondary: "Croatia"},
	CY: {primary: "CY", secondary: "Cyprus"},
	CZ: {primary: "CZ", secondary: "Czech Republic"},
	DK: {primary: "DK", secondary: "Denmark"},
	EE: {primary: "EE", secondary: "Estonia"},
	FI: {primary: "FI", secondary: "Finland"},
	FR: {primary: "FR", secondary: "France"},
	DE: {primary: "DE", secondary: "Germany"},
	HU: {primary: "HU", secondary: "Hungary"},
	IE: {primary: "IE", secondary: "Republic of Ireland"},
	IT: {primary: "IT", secondary: "Italy"},
	LU: {primary: "LU", secondary: "Luxembourg"},
	MT: {primary: "MT", secondary: "Malta"},
	NL: {primary: "NL", secondary: "Netherlands"},
	NO: {primary: "NO", secondary: "Norway"},
	PL: {primary: "PL", secondary: "Poland"},
	PT: {primary: "PT", secondary: "Portugal"},
	RO: {primary: "RO", secondary: "Romania"},
	SK: {primary: "SK", secondary: "Slovak Republic"},
	SI: {primary: "SI", secondary: "Slovenia"},
	ES: {primary: "ES", secondary: "Spain"},
	SE: {primary: "SE", secondary: "Sweden"},
	AU: {primary: "AU", secondary: "Australia"},
	CA: {primary: "CA", secondary: "Canada"},
	NZ: {primary: "NZ", secondary: "New Zealand"},
	ZA: {primary: "ZA", secondary: "South Africa"},
	CH: {primary: "CH", secondary: "Switzerland"},
	GB: {primary: "GB", secondary: "United Kingdom"},
    };

    export const COUNTRY_VALUES = Object.keys(COUNTRY_NAMES)